import {randomUUID} from 'node:crypto';
import {RunnerJobClient,dispatchCompletion} from '@thierryc/plotter-core/client';
import {openRunnerTransport} from './runner-transport.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {preparePaths,prepareLayerJob,importPrepared,JobSequence,PlotterSession,machineProfile,defaultPen,applyHandling,capabilities,executionSvg,validatePreparedJob,CheckpointIndex,variedCopy,automaticPlacement,rectangle,prepareScene,orderedLayerRuns} from '@thierryc/plotter-core';
import {VirtualEbb,VirtualClock} from '@thierryc/plotter-core/virtual';
import {readSvgScene,svgScenePaths} from '../src/svg-scene.ts';
const args=process.argv.slice(2),value=flag=>{const i=args.indexOf(flag);return i<0?undefined:args[i+1];};
if(args.includes('--help')||!args.length){console.log(`Plot-It CLI\n\n  npm run plot:cli -- --input paths.json --virtual\n  npm run plot:cli -- --input drawing.svg --export output/prepared\n  npm run plot:cli -- --input drawing.svg --device /dev/cu.usbmodem... --firmware 2.8.1\n\nDefault is prepare/export only. Physical execution requires an explicit --device.\n  --input FILE       Normalized paths JSON, prepared v2 JSON, or SVG\n  --settings FILE    Core PlotOptions JSON overrides\n  --profile ID      axidraw, axidraw-a3, xylodraw, nextdraw-8511/1117/2234\n  --firmware VER    Prepared target (default 2.8.1; modern virtual 3.1.7)\n  --scurve          Explicit EBB 3.1.7 S-curve backend\n  --constant        Constant drawing policy
  --handling NAME   custom, technical, handwriting, sketching\n  --copies N        Finite copies, or continuous\n  --gap-ms N        Inter-copy wait\n  --export DIR      Save prepared JSON and draw/travel SVGs\n  --virtual         Execute on virtual EBB without USB\n  --device PATH     Execute on exactly this physical USB device
  --runner URL      Submit/start through the existing runner API
  --origin URL      Allowed Origin for runner control
  --webhook URL     Optional completion delivery after local execution\n  --home            Explicit NextDraw homing before drawing\n  --list            List EBB USB paths; does not connect
  --info            Read name, firmware, capabilities, profile and ADC
  --rename NAME     Explicit persistent nickname (max 16 ASCII characters)\n  --occlusion       Remove lines beneath later opaque fills\n  --offset-mm N     Start at drawing distance, not XY translation
  --checkpoint FILE Resume a validated settled checkpoint
  --adjust-mm N     Resume overlap adjustment (negative redraws)
  --continue        Require Continue after each inter-copy timer
  --vary-starts     Deterministic varied closed starts; --seed N
  --auto-place      SVG portrait/landscape placement without scaling
  --auto-continue   Virtual-only gate acceptance
  --help            This help\n\nSVG: paths/basic shapes, affine transforms, inline styles and user-space clip paths.\nText must be converted to paths; external images/use, filters, masks, stylesheets and\nobjectBoundingBox clips are explicit unsupported cases.`);process.exit(0);}
if(args.includes('--list')){const {listEbbPorts}=await import('@thierryc/plotter-core/node');console.log(JSON.stringify(await listEbbPorts(),null,2));process.exit(0);}
if(args.includes('--virtual')&&value('--device'))throw new Error('Choose either virtual execution or an explicit USB device');
if(args.includes('--info')||value('--rename')!==undefined){
 if(!args.includes('--virtual')&&!value('--device'))throw new Error('Info/rename requires --virtual or an explicit --device');
 const profile=machineProfile(value('--profile')??'xylodraw');let session;
 if(args.includes('--virtual')){const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:value('--firmware')??'2.8.1'});session=new PlotterSession(board.createTransport(),clock,profile);}else{const {nodeClock,openNodeTransport}=await import('@thierryc/plotter-core/node');session=new PlotterSession(await openNodeTransport(value('--device')),nodeClock,profile);}
 try{await session.connect();if(value('--rename')!==undefined)await session.rename(value('--rename'));console.log(JSON.stringify({virtual:args.includes('--virtual'),device:value('--device')??null,name:await session.readName(),firmware:session.firmware?.version,capabilities:capabilities(session.firmware),profile,power:session.power,adcUnits:'raw counts / 1023'},null,2));}finally{if(session.connected)await session.disconnect();}process.exit(0);
}
const webhook=value('--webhook')?new URL(value('--webhook')):null;if(webhook&&!['http:','https:'].includes(webhook.protocol))throw new Error('Webhook requires HTTP(S)');
const input=value('--input');if(!input)throw new Error('Specify --input FILE');const source=await readFile(input,'utf8');if(source.length>32*1024*1024)throw new Error('Input exceeds 32 MiB');
let scene,paths,job;const firmware=value('--firmware')??(args.includes('--scurve')?'3.1.7':'2.8.1'),profile=machineProfile(value('--profile')??'xylodraw');
const overrides=value('--settings')?JSON.parse(await readFile(value('--settings'),'utf8')):{};
let options={profile,pen:{...defaultPen,up:profile.servoKind==='brushless'?60:30,down:profile.servoKind==='brushless'?30:52},speed:35,travelSpeed:60,acceleration:200,travelAcceleration:300,cornering:.127,maxPenDownMm:30,returnToOrigin:true,drawingMode:args.includes('--constant')?'constant':'profiled',backend:args.includes('--scurve')?'t3':'sm',firmware,drawingJerk:500000,travelJerk:330200,...overrides};
options.pen={...defaultPen,up:profile.servoKind==='brushless'?60:30,down:profile.servoKind==='brushless'?30:52,...overrides.pen};options.profile={...profile,...overrides.profile};
const resolved=applyHandling(options,value('--handling')??overrides.handling??'custom');options={...resolved,...overrides,profile:{...resolved.profile,...overrides.profile},pen:{...resolved.pen,...overrides.pen}};
const offset=Number(value('--offset-mm')??0);
const repeat={varyClosedStarts:args.includes('--vary-starts'),seed:Number(value('--seed')??1),copies:value('--copies')==='continuous'?'continuous':Number(value('--copies')??1),intervalMs:Number(value('--gap-ms')??0),requireContinue:args.includes('--continue')};
if(input.toLowerCase().endsWith('.svg')){
 if(/<!DOCTYPE|<!ENTITY/i.test(source))throw new Error('SVG entity declarations are unsupported');const {JSDOM}=await import('jsdom');const dom=new JSDOM(source,{contentType:'image/svg+xml'});scene=readSvgScene(dom.window.document.documentElement,options.curveToleranceMm??.05);paths=svgScenePaths(scene,args.includes('--occlusion'));for(const layer of scene.layers)layer.paths=paths.filter(p=>p.layerId===layer.id);if(args.includes('--auto-place'))paths=automaticPlacement(paths,scene.width,scene.height).paths;if(options.profile.bounds){const b=options.profile.bounds,swapped=options.profile.rotation===90||options.profile.rotation===270;paths=prepareScene([{id:'drawing',paths}],{machine:rectangle(swapped?b.height:b.width,swapped?b.width:b.height)});}for(const layer of scene.layers)layer.paths=paths.filter(p=>p.layerId===layer.id);job=prepareLayerJob(orderedLayerRuns(paths,scene.layers),options,repeat,offset);dom.window.close();
}else{const parsed=JSON.parse(source);if(parsed.version===2){job=importPrepared(source);paths=job.paths;}else{paths=Array.isArray(parsed)?parsed:parsed.paths;job=preparePaths(paths,options,repeat,offset);}}
if(value('--checkpoint')){const checkpoint=JSON.parse(await readFile(value('--checkpoint'),'utf8'));const {resumeCheckpoint}=await import('@thierryc/plotter-core');const resumed=resumeCheckpoint(job.program,checkpoint,Number(value('--adjust-mm')??0));const start=Math.max(0,checkpoint.drawingMm+Number(value('--adjust-mm')??0));job=job.layers?prepareLayerJob(job.layers,job.options,job.repeat,start):preparePaths(job.paths,job.options,job.repeat,start);if(JSON.stringify(job.program)!==JSON.stringify(resumed))throw new Error('Resume identity mismatch');}
validatePreparedJob(job);console.log(JSON.stringify({digest:job.digest,target:job.target,drawingMm:job.program.drawingMm,travelMm:job.program.travelMm,durationMs:job.program.durationMs,records:job.program.records.length,repeat:job.repeat},null,2));
const output=value('--export');if(output){await mkdir(output,{recursive:true});await writeFile(`${output}/prepared.json`,JSON.stringify(job));for(const mode of ['draw','travel','all'])await writeFile(`${output}/${mode}.svg`,executionSvg(job.program,mode));}
if(value('--runner')){if(args.includes('--virtual')||value('--device'))throw new Error('Choose one execution destination');const transport=await openRunnerTransport(value('--runner'),value('--origin'));const clock={now:()=>performance.now(),sleep:ms=>new Promise(resolve=>setTimeout(resolve,ms)),schedule:(ms,fn)=>{const timer=setTimeout(fn,ms);return()=>clearTimeout(timer);}};const client=new RunnerJobClient(transport,randomUUID,clock);try{const accepted=await client.submit(job);if(args.includes('--home'))await client.command('home',{jobId:accepted.id});await client.start(accepted.id);console.log(JSON.stringify(await client.wait(accepted.id)));}finally{transport.close();}process.exit(0);}
if(!args.includes('--virtual')&&!value('--device'))process.exit(0);
if(job.repeat.copies==='continuous'&&args.includes('--virtual'))throw new Error('Use the real-time virtual monitor for interactive continuous runs.');
if(!process.stdin.isTTY&&(job.repeat.requireContinue||job.program.records.some(r=>r.kind==='tool'||r.kind==='pause'))&&!args.includes('--auto-continue'))throw new Error('This job needs a terminal Continue gate; use --auto-continue only for virtual acceptance.');
if(args.includes('--auto-continue')&&!args.includes('--virtual'))throw new Error('Automatic Continue is virtual-only.');
let session,board,clock;if(args.includes('--virtual')){clock=new VirtualClock();board=new VirtualEbb(clock,{firmware:job.target.firmware,fragmentBytes:1,...(args.includes('--home')?{homingMechanics:{x:20,y:40,stepsPerMm:job.options.profile.stepsPerMm}}:{})});session=new PlotterSession(board.createTransport(),clock,job.options.profile);}else{const {nodeClock,openNodeTransport}=await import('@thierryc/plotter-core/node');clock=nodeClock;session=new PlotterSession(await openNodeTransport(value('--device')),clock,job.options.profile);}
await session.connect();session.configure(job.options.pen);if(args.includes('--home'))await session.home();const sequence=new JobSequence(session,clock);let checkpointIndex=new CheckpointIndex(job.program),lastCheckpoint;sequence.onProgram=plan=>{checkpointIndex=new CheckpointIndex(plan);};session.subscribe(e=>{if(e.kind==='record'&&e.phase==='settled')lastCheckpoint=checkpointIndex.at(e.recordId,sequence.status.copy||1);});process.on('SIGINT',()=>sequence.cancel());let gate=false;const ask=async()=>{if(gate)return;gate=true;try{if(board&&args.includes('--auto-continue'))session.resume();else{const {createInterface}=await import('node:readline/promises');const rl=createInterface({input:process.stdin,output:process.stdout});await rl.question('Load the next pen and press Enter: ');rl.close();session.resume();}}finally{gate=false;}};session.subscribe(e=>{if(e.kind==='state'&&e.state==='tool-change')void ask().catch(()=>sequence.cancel());});
sequence.onStatus=status=>{if(status.state==='continue'){if(board&&args.includes('--auto-continue'))sequence.continue();else void (async()=>{if(gate)return;gate=true;const {createInterface}=await import('node:readline/promises');const rl=createInterface({input:process.stdin,output:process.stdout});await rl.question('Continue layer: press Enter. ');rl.close();gate=false;sequence.continue();})().catch(()=>sequence.cancel());}if(status.remainingMs%1000===0)console.log(`Copy ${status.copy} · ${status.state} · wait ${status.remainingMs} ms`);};
try{const segments=[{id:'drawing',plan:job.program}];await sequence.run(segments,job.repeat,job.repeat.varyClosedStarts?copy=>[{id:'drawing',plan:variedCopy(job.paths,job.options,copy,job.repeat.seed,job.layers,job.startAtMm)}]:undefined);console.log(JSON.stringify({state:sequence.status.state,virtual:!!board,position:board?.position,penUp:board?.penUp}));if(webhook){const address=webhook;dispatchCompletion({version:1,jobDigest:job.digest,state:sequence.status.state,elapsedMs:sequence.elapsedMs,virtual:!!board},async event=>{const response=await fetch(address,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(event),signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`Webhook HTTP ${response.status}`);},error=>console.error('Completion delivery failed:',String(error)));}}finally{if(output&&lastCheckpoint)await writeFile(`${output}/checkpoint.json`,JSON.stringify(lastCheckpoint));if(session.connected&&!session.busy)await session.disconnect();}
