// @vitest-environment jsdom
import {describe,it,expect} from 'vitest';

import {readSvgScene,svgScenePaths} from './svg-scene';
import {contains,rectangle,automaticPlacement,parseLayerControls} from '@thierryc/plotter-core';
const scene=(content:string)=>{const doc=new DOMParser().parseFromString(`<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" viewBox="0 0 100 100" width="100mm" height="100mm">${content}</svg>`,'image/svg+xml');return readSvgScene(doc.documentElement);};
describe('shared SVG scene preparation',()=>{
 it('keeps exact polyline corners and separate subpaths with transforms',()=>{const s=scene('<g transform="translate(10,20)"><path d="M0 0 L10 0 L10 10 M30 0 L40 0" fill="none"/></g>');expect(s.items[0]!.paths[0]!.points).toEqual([{x:10,y:20},{x:20,y:20},{x:20,y:30}]);expect(s.items[0]!.paths).toHaveLength(2);});
 it('flattens cubic, quadratic and elliptical paths at a shared physical tolerance',()=>{const s=scene('<path d="M0 0 C0 20 20 20 20 0 Q30 20 40 0 A10 10 0 0 1 60 0" fill="none"/>');const p=s.items[0]!.paths[0]!.points;expect(p[0]).toEqual({x:0,y:0});expect(p.at(-1)!.x).toBeCloseTo(60);expect(p.length).toBeGreaterThan(20);});
 it('removes hidden lines before any pen ordering and keeps holes for even-odd fills',()=>{const s=scene('<path d="M0 10 L30 10" fill="none"/><path d="M5 5 L25 5 L25 15 L5 15 Z M10 7 L20 7 L20 13 L10 13 Z" fill-rule="evenodd" fill="white" stroke="none"/>');const p=svgScenePaths(s,true);expect(p.map(p=>p.points.map(q=>q.x))).toEqual([[0,5],[10,20],[25,30]]);});
 it('applies user-space clipping without pen-down connectors',()=>{const s=scene('<defs><clipPath id="c"><rect x="5" y="5" width="10" height="10"/></clipPath></defs><path d="M0 10 L30 10" fill="none" clip-path="url(#c)"/>');expect(svgScenePaths(s)[0]!.points).toEqual([{x:5,y:10},{x:15,y:10}]);});
 it('retains a parent clip in its own coordinate system across child transforms',()=>{const s=scene('<defs><clipPath id="c" transform="translate(2,0)"><rect x="5" y="5" width="10" height="10"/></clipPath></defs><g clip-path="url(#c)"><path transform="translate(10,0)" d="M-10 10 L20 10" fill="none"/></g>');expect(svgScenePaths(s)[0]!.points).toEqual([{x:7,y:10},{x:17,y:10}]);});
 it('does not use a transparent parent group as an opaque occluder',()=>{const s=scene('<path d="M0 10 L30 10" fill="none"/><g opacity=".5"><rect x="5" y="5" width="10" height="10" fill="white" stroke="none"/></g>');expect(svgScenePaths(s,true)[0]!.points).toEqual([{x:0,y:10},{x:30,y:10}]);});
 it('preserves empty-layer timing and typed layer annotations',()=>{const s=scene('<g inkscape:groupmode="layer" inkscape:label="!1+d2000 Waiting" id="wait"/><g inkscape:groupmode="layer" inkscape:label="2+s50+h65+g0+M3 Layer" id="drawing"><line x1="1" y1="1" x2="5" y2="1"/></g>');expect(s.layers[0]).toMatchObject({id:'wait',pause:true,delayMs:2000,paths:[]});expect(parseLayerControls('2+s50+h65+g0+M3 Layer')).toMatchObject({speedPercent:50,penDown:65,optimization:0,handlingMetadata:3});});
 it('rejects unsupported rendering rather than silently altering a physical job',()=>{for(const content of ['<text>hello</text>','<path d="M0 0 L10 10" mask="url(#m)"/>','<use href="x.svg"/>'])expect(()=>scene(content)).toThrow(/Unsupported|unsupported/);});
 it('chooses portrait/landscape placement without silently rescaling artwork',()=>{const placed=automaticPlacement([{tool:'black',points:[{x:0,y:0},{x:100,y:20}]}],30,110,2);expect(placed.rotation).toBe(90);expect(Math.hypot(placed.paths[0]!.points[1]!.x-placed.paths[0]!.points[0]!.x,placed.paths[0]!.points[1]!.y-placed.paths[0]!.points[0]!.y)).toBeCloseTo(Math.hypot(100,20));expect(contains(rectangle(30,110),placed.paths[0]!.points[0]!)).toBe(true);});
});
