import {it,expect} from 'vitest';
import {PlotterSession,compileJob,compileLayerProgram,prepareLayerJob,validatePreparedJob,resumeAtDistance,machineProfile,defaultPen,servoPulse,variedCopy,JobSequence,type PlotOptions} from './index.js';
import {VirtualClock,VirtualEbb} from './virtual/index.js';
import {dispatchCompletion,RunnerJobClient} from './client.js';
const options:PlotOptions={profile:machineProfile('xylodraw',0),pen:{...defaultPen,up:30,down:52},speed:35,travelSpeed:60,acceleration:200,travelAcceleration:400,cornering:.127,maxPenDownMm:15,returnToOrigin:true,drawingMode:'profiled'};
const paths=[{tool:'black',points:[{x:10,y:10},{x:45,y:10}]}];
it.each(['sm','t3']as const)('executes a composite %s program and resumed layers with waits and restored pen settings',async backend=>{
 const o={...options,backend,firmware:backend==='t3'?'3.1.7':'2.8.1'},layers=[{id:'first',name:'First',paths,overrides:{speed:10,penDown:70}},{id:'empty',name:'Dry',paths:[],pause:true,delayMs:400},{id:'last',name:'Last',paths,overrides:{penDown:40}}],job=prepareLayerJob(layers,o);
 expect(validatePreparedJob(job)).toEqual(job);const resumed=resumeAtDistance(job.program,5);expect(resumed.records.some(r=>r.kind==='delay'&&r.durationMs===400)).toBe(true);expect(resumed.records.some(r=>r.kind==='pause')).toBe(true);expect(resumed.records.filter(r=>r.settings).map(r=>r.settings!.pen.down)).toEqual([70,40,52]);
 for(const program of [job.program,resumed]){const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:backend==='t3'?'3.1.7':'2.8.1'}),session=new PlotterSession(board.createTransport(),clock,o.profile);await session.connect();session.subscribe(e=>{if(e.state==='tool-change')session.resume();});await session.run(program);const lowers=board.trace.filter(t=>t.phase==='completed'&&t.command.startsWith('SP,0,'));expect(lowers.some(t=>t.pulse===servoPulse(70,o.profile))).toBe(true);expect(lowers.some(t=>t.pulse===servoPulse(40,o.profile))).toBe(true);expect(board.position).toEqual({m1:0,m2:0});expect(board.penUp).toBe(true);expect(board.servo.get(5)).toBe(servoPulse(52,o.profile));}
});
it('refuses corrupted observed counters and requires explicit recovery before a new job',async()=>{const clock=new VirtualClock();let corrupt=true;const board=new VirtualEbb(clock,{onCommand:c=>{if(c==='QS'&&corrupt&&board.trace.some(t=>t.phase==='completed'&&!t.penUp)){board.position.m1++;corrupt=false;}}}),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();await expect(session.run(compileJob(paths,options))).rejects.toThrow(/position differs/);expect(session.origin.recoveryRequired).toBe(true);const count=board.commandCount;await expect(session.run(compileJob(paths,options))).rejects.toThrow(/Restore/);expect(board.commandCount).toBe(count);await session.setOrigin();expect(await session.run(compileJob(paths,options))).toBe('finished');});
it('isolates rejected asynchronous observers and arms modern supply monitoring on SM',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:'3.1.7'}),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();session.subscribe(async()=>{throw new Error('UI failed');});expect(await session.run(compileJob(paths,options))).toBe('finished');expect(board.commands).toContain('CU,60,250');});
it('preflights interactive geometry, clips the drawing ray and synchronizes B3 only after settled pen changes',async()=>{const clock=new VirtualClock(),profile={...options.profile,bounds:{width:100,height:100}},board=new VirtualEbb(clock),session=new PlotterSession(board.createTransport(),clock,profile),o={...options,profile,maxPenDownMm:0,pen:{...options.pen,synchronizedB3:true}};await session.connect();await session.setOrigin();const count=board.commandCount;await expect(session.drawTo({x:NaN,y:1},o)).rejects.toThrow();expect(board.commandCount).toBe(count);await session.moveTo({x:10,y:10},o);await session.drawTo({x:200,y:50},o);expect(await session.observedPosition()).toEqual({x:100,y:28.94});expect(session.intendedPosition).toEqual({x:200,y:50});expect(board.penUp).toBe(true);expect(board.gpio.get(3)).toBe(0);});
it('preserves final return preference while forcing nonfinal copies to origin',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();const sequence=new JobSequence(session,clock),programs:boolean[]=[];sequence.onProgram=plan=>programs.push(plan.options.returnToOrigin);sequence.onStatus=s=>{if(s.state==='waiting'){expect(board.penUp).toBe(true);expect(board.position).toEqual({m1:0,m2:0});}};await sequence.run([{id:'drawing',plan:compileJob(paths,{...options,returnToOrigin:false})}],{copies:2,intervalMs:1000,requireContinue:false});expect(programs).toEqual([true,false]);expect(board.position.m1).not.toBe(0);expect(session.origin.recoveryRequired).toBe(true);});
it('varies closed starts deterministically without changing the edges',()=>{const closed=[{tool:'black',points:[{x:1,y:1},{x:4,y:1},{x:4,y:4},{x:1,y:4},{x:1,y:1}]}];const a=variedCopy(closed,options,2,23),b=variedCopy(closed,options,2,23);expect(a).toEqual(b);expect(a.drawingMm).toBeCloseTo(12,2);});
it('completion delivery failure cannot change plotting success or submit another job',async()=>{let reported=false,delivered=0;dispatchCompletion({version:1,jobDigest:'abc',state:'finished',elapsedMs:10,virtual:true},async()=>{delivered++;throw new Error('offline');},()=>{reported=true;});await new Promise(resolve=>setTimeout(resolve,0));expect(delivered).toBe(1);expect(reported).toBe(true);});
it('portable client polls completion without automatically restarting interrupted jobs',async()=>{const clock=new VirtualClock();let controls=0;const client=new RunnerJobClient({get:async()=>({status:'interrupted'}),post:async()=>({id:'test',status:'pending'}),control:async()=>{controls++;}},()=> 'request',clock);expect((await client.wait('test')).status).toBe('interrupted');expect(controls).toBe(0);});
it('virtual timers fire at their scheduled time even within a long host sleep',()=>{const clock=new VirtualClock(),seen:number[]=[];clock.schedule(20,()=>seen.push(clock.now()));clock.schedule(40,()=>seen.push(clock.now()));clock.advance(100);expect(seen).toEqual([20,40]);expect(clock.now()).toBe(100);});
it('retains empty delay/pause layers without drawing connectors',()=>{const plan=compileLayerProgram([{id:'empty',name:'Wait',paths:[],delayMs:150,pause:true}],options);expect(plan.records.some(r=>r.kind==='motor')).toBe(false);expect(plan.records.filter(r=>r.kind==='pause'||r.kind==='delay').map(r=>r.kind)).toEqual(['pause','delay']);});

it.each([false,true])('keeps fragmented nickname whitespace and CRLF framing aligned (future=%s)',async future=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:'3.1.7',futureReplies:future,fragmentBytes:1}),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();await session.rename('  Plot One  ');expect(await session.readName()).toBe('  Plot One  ');expect((await session.checkPower())!.state).toBe('detected');await session.rename('');expect(await session.readName()).toBe('');});

it('keeps an externally observed transient supply fault latched until explicit origin recovery',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:'3.1.7'}),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();await session.setOrigin();board.losePower();await expect(session.pollStatus()).rejects.toThrow(/origin/);board.supplyAdc=300;const count=board.commandCount;await expect(session.run(compileJob(paths,options))).rejects.toThrow(/Restore/);expect(board.commandCount).toBe(count);await session.setOrigin();expect(await session.run(compileJob(paths,options))).toBe('finished');});

it.each(['3.0.2','3.1.0','3.1.6']as const)('uses SM and restored pen timing on compatibility firmware %s',async firmware=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware}),session=new PlotterSession(board.createTransport(),clock,options.profile),o={...options,backend:'sm' as const,firmware};await session.connect();await session.setPen(o.pen.down);await session.run(compileJob(paths,o,'bounds'));const cut=board.trace.length;await session.run(compileJob(paths,o));expect(board.trace.slice(cut).some(t=>t.phase==='started'&&t.command.startsWith('SM,')&&!t.penUp)).toBe(true);expect(board.commands.some(c=>c.startsWith('T3,'))).toBe(false);expect(board.position).toEqual({m1:0,m2:0});expect(board.penUp).toBe(true);});

it('monitors supply while a paused plot awaits human input',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:'3.1.7'}),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();const plan=compileJob(paths,options);let once=false;session.subscribe(e=>{if(e.kind==='record'&&e.phase==='settled'&&plan.records[e.recordId!]?.penDown&&!once){once=true;session.pause();}if(e.state==='paused'){clock.schedule(50,()=>board.losePower());void Promise.resolve().then(()=>clock.advance(100));}});await expect(session.run(plan)).rejects.toThrow(/origin|supply/i);expect(session.origin.recoveryRequired).toBe(true);expect(board.penUp).toBe(true);});

it('allows offline profile editing but refuses NextDraw controls on connected 2.8.1 before serial writes',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();session.configure(options.pen,machineProfile('nextdraw-8511'));const count=board.commandCount;await expect(session.setPen(30)).rejects.toThrow(/3.0.2/);await expect(session.setOrigin()).rejects.toThrow(/3.0.2/);await expect(session.home()).rejects.toThrow(/3.0.2/);expect(board.commandCount).toBe(count);});

it('requires recovery when a future ES acknowledgement omits its interruption payload',async()=>{const clock=new VirtualClock(),board=new VirtualEbb(clock,{firmware:'3.1.7',futureReplies:true,fragmentBytes:4096}),old=board.createTransport();await old.write(new TextEncoder().encode('EM,2,2\rSM,1000,50,50\r'));await old.close();const bytes=board.createTransport(),transport={...bytes,read:async()=>{const data=await bytes.read();if(data&&new TextDecoder().decode(data).startsWith('ES,'))return new TextEncoder().encode('ES\r\n');return data;}},session=new PlotterSession(transport,clock,options.profile);await session.connect();await expect(session.run(compileJob(paths,options))).rejects.toThrow(/interrupted/);expect(session.origin.recoveryRequired).toBe(true);expect(board.penUp).toBe(true);});
