import {describe,it,expect} from 'vitest';
import {createHash} from 'node:crypto';
import {sha256} from './identity.js';
import {compileJob} from './compiler.js';
import {preparePaths,validatePreparedJob,exportPrepared,importPrepared} from './prepared-job.js';
import {JobSequence,compileLayers} from './sequence.js';
import {checkpointAt,resumeCheckpoint,resumeAtDistance} from './resume.js';
import {machineProfile} from './profiles.js';
import {defaultPen,servoCommands} from './pen.js';
import {PlotterSession} from './session.js';
import {VirtualClock,VirtualEbb} from './virtual/index.js';
import type {PlotOptions} from './types.js';
const options:PlotOptions={profile:machineProfile('xylodraw',0),pen:{...defaultPen,up:30,down:52},speed:35,travelSpeed:60,acceleration:200,travelAcceleration:300,cornering:.127,maxPenDownMm:15,returnToOrigin:true,drawingMode:'profiled'};
const paths=[{tool:'black',points:[{x:10,y:10},{x:45,y:10}]}];
async function fixture(){const clock=new VirtualClock(),board=new VirtualEbb(clock),session=new PlotterSession(board.createTransport(),clock,options.profile);await session.connect();return{clock,board,session,sequence:new JobSequence(session,clock)};}
describe('sequence, snapshots and resume',()=>{
 it('matches Node SHA-256 for ASCII, Unicode and long input',()=>{for(const text of ['', 'abc','é 🖊️','a'.repeat(10000)])expect(sha256(text)).toBe(createHash('sha256').update(text).digest('hex'));});
 it('recompiles portable version-2 snapshots and rejects modified settings/records',()=>{const job=preparePaths(paths,options);expect(importPrepared(exportPrepared(job))).toEqual(job);const tampered=structuredClone(job);tampered.options.speed=40;expect(()=>validatePreparedJob(tampered)).toThrow(/match/);const corrupted=structuredClone(job);corrupted.program.records[2]!.durationMs++;expect(()=>validatePreparedJob(corrupted)).toThrow();});
 it('runs three copies with ten-second gaps, Up at origin, and no final delay',async()=>{const {sequence,clock,board}=await fixture(),plan=compileJob(paths,options),gaps:number[]=[];sequence.onStatus=status=>{if(status.state==='waiting'){expect(board.penUp).toBe(true);expect(board.position).toEqual({m1:0,m2:0});gaps.push(status.remainingMs);}};await sequence.run([{id:'drawing',plan}],{copies:3,intervalMs:10000,requireContinue:false});expect(sequence.status.copy).toBe(3);expect(gaps.filter(ms=>ms===10000)).toHaveLength(2);expect(clock.now()).toBeGreaterThan(plan.durationMs*3+20000);expect(sequence.status.state).toBe('finished');});
 it('freezes a timer on Pause and resumes the remaining four seconds',async()=>{const {sequence,clock}=await fixture();let paused=false,frozen=0;sequence.onStatus=status=>{if(!paused&&status.state==='waiting'&&status.remainingMs===4000){paused=true;frozen=clock.now();sequence.pause();clock.schedule(3000,()=>{expect(sequence.status.remainingMs).toBe(4000);sequence.resume();});}};await sequence.run([{id:'drawing',plan:compileJob(paths,options)}],{copies:2,intervalMs:10000,requireContinue:false});expect(paused).toBe(true);expect(clock.now()-frozen).toBeGreaterThan(7000);});
 it('stops continuous runs during the gap without starting another copy',async()=>{const {sequence,board}=await fixture();sequence.onStatus=status=>{if(status.state==='waiting'&&status.copy===2)sequence.stop();};await sequence.run([{id:'drawing',plan:compileJob(paths,options)}],{copies:'continuous',intervalMs:10000,requireContinue:false});expect(sequence.status.copy).toBe(2);expect(sequence.status.state).toBe('stopped');expect(board.penUp).toBe(true);});
 it('cancels a Continue gate after the timer, and never launches the next copy',async()=>{const {sequence}=await fixture();let completeTimer=false;sequence.onStatus=status=>{if(status.state==='continue'){completeTimer=true;expect(status.remainingMs).toBe(0);sequence.cancel();}};await sequence.run([{id:'drawing',plan:compileJob(paths,options)}],{copies:3,intervalMs:1000,requireContinue:true});expect(completeTimer).toBe(true);expect(sequence.status.copy).toBe(1);expect(sequence.status.state).toBe('cancelled');});
 it('preserves empty layer waits and restores height/speed outside overrides',async()=>{const {sequence,board}=await fixture();const segments=compileLayers([{id:'empty',name:'wait',paths:[],delayMs:250,pause:true},{id:'first',name:'first',paths,overrides:{speed:10,penDown:60}},{id:'second',name:'second',paths}],options);sequence.onStatus=status=>{if(status.state==='continue')sequence.continue();};await sequence.run(segments);expect(segments[1]!.plan!.options.speed).toBe(10);expect(segments[2]!.plan!.options.pen.down).toBe(52);const lowers=board.trace.filter(t=>t.phase==='started'&&t.command.startsWith('SP,0'));expect(new Set(lowers.map(t=>t.pulse)).size).toBeGreaterThanOrEqual(1);expect(board.servo.get(5)).toBe(Number(servoCommands(options.pen,options.profile)[1]!.split(',').at(-1)));});
 it('resumes inside a reload-limited stroke, supports overlap and rejects stale checkpoints',async()=>{const plan=compileJob(paths,options),settled=plan.records.findIndex(r=>r.kind==='pen'&&!r.penDown&&r.id>0),checkpoint=checkpointAt(plan,settled),resumed=resumeCheckpoint(plan,checkpoint,-2);expect(resumed.drawingMm).toBeCloseTo(plan.drawingMm-checkpoint.drawingMm+2,1);expect(resumed.records[0]).toMatchObject({kind:'pen',penDown:false});expect(()=>resumeCheckpoint(plan,{...checkpoint,drawingMm:999})).toThrow(/Corrupted/);expect(()=>resumeAtDistance(plan,plan.drawingMm+1)).toThrow(/end/);});
 it('enables model-specific brushless configuration independently from firmware',()=>{const profile=machineProfile('nextdraw-1117',90,16);expect(profile).toMatchObject({stepsPerMm:80,servoPin:2,servoMin:5400,servoMax:12600,servoChannels:1});expect(profile.bounds!.width).toBeCloseTo(430.022);expect(servoCommands(defaultPen,profile)).toContain('SC,8,1');expect(machineProfile('axidraw')).toMatchObject({servoMin:28000,servoMax:7500});});
});
